CREATE TABLE IF NOT EXISTS EVENT
(
    KEY bigint,
    TIMESTAMP bigint,
    VALUETYPE varchar,
    INTENT varchar,
    PROCESSDEFINITIONKEY bigint,
    EVENTTEXT varchar
);


CREATE TABLE IF NOT EXISTS PROCESSDEFINITION
(
    ID bigint,
    PROCESSDEFINITIONKEY varchar,
    VERSION int,
    BPMNPROCESSID varchar,
    RESOURCENAME varchar
);